VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsFormulaTobacco"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'烟叶角色类(用于存放一个烟叶角色的数据及其相关计算)
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

Public yy As String
Public pc As String
Public dpxs As Integer
