VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsSupplyTobacco"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'烟叶领料类(用于存放一个烟叶领料的数据及其相关计算)
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Public yy As String
Public pc As String
Public num As Integer

