SET SCHEMA = YYZY;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,DB2INST2;

CREATE VIEW YYZY.V_YYZY_YYKC_WHB
    ( YYDM, YYMC, YYNF, YYKCJS, KCSL,KCLX )
AS
WITH YSSJ AS ( 
  SELECT A.LSBH, A.YYDM, A.YYMC, A.YYCDDM, A.YYLBDM, A.YYKBDM, A.YYDJDM, A.YYNF, A.YYBZDM, A.KSRQ, A.JSRQ, B.GNW 
  FROM DIM.T_DIM_YYZY_YYZDB A LEFT JOIN YYZY.T_YYZY_YYZDBMX B ON A.YYDM = B.YYDM 
  WHERE A.JSRQ >= CURRENT DATE AND B.GNW IS NOT NULL) , CPFNF(C_CPFNF) AS ( VALUES YEAR(CURRENT DATE - 6 MONTH)) , GWYY(YYDM, YYNF, YYKCJS) AS ( VALUES('11KY22BRA010', 2011, 23750),('11KY22ARG010', 2011, 1000),( '11KY22ZWE010', 2011, 46250),('11KY22ZMB010', 2011, 1500),('11KY22MWI020', 2011, 1000),('11KY22USA020', 2011, 10000),('11XL22TUR010', 2011, 300)) , YYNF(C_YYNF) AS ( VALUES YEAR(CURRENT DATE)) , YYBKC AS ( 
  SELECT A.YYDM, A.YYNF, VALUE(SUM(A.KCJS * 1.00 / ( CASE WHEN B.YYMC LIKE '%香料%' AND C.CDLX = 1 THEN 6 ELSE 1 
  END)), 0) AS YYKCJS, SUM(A.KCSL) AS KCSL 
  FROM YYZY.T_YYZY_YYKC_NEW AS A LEFT JOIN DIM.T_DIM_YYZY_YYZDB AS B ON A.YYDM = B.YYDM AND B.JSRQ > CURRENT DATE LEFT JOIN DIM.T_DIM_YYZY_YYCD AS C ON C.YYCDDM = B.YYCDDM AND C.JSRQ > CURRENT DATE LEFT JOIN CPFNF ON 1 = 1 LEFT JOIN YSSJ D ON A.YYDM = D.YYDM 
  WHERE 1 = 1 AND A.YYCKDM NOT IN (74, 58, 50) AND A.KCJS > 0 AND A.YYNF < YEAR(CURRENT DATE - 6 MONTH) GROUP BY A.YYDM, A.YYNF 
  UNION ALL 
  SELECT A.YYDM, A.YYNF, VALUE(SUM(A.KCJS * 1.00 / ( CASE WHEN B.YYMC LIKE '%香料%' AND C.CDLX = 1 THEN 6 ELSE 1 
  END)), 0) AS YYKCJS, SUM(A.KCSL) AS KCSL 
  FROM YYZY.T_YYZY_YYKC_NEW AS A LEFT JOIN DIM.T_DIM_YYZY_YYZDB AS B ON A.YYDM = B.YYDM AND B.JSRQ > CURRENT DATE LEFT JOIN DIM.T_DIM_YYZY_YYCD AS C ON C.YYCDDM = B.YYCDDM AND C.JSRQ > CURRENT DATE LEFT JOIN CPFNF ON 1 = 1 LEFT JOIN YSSJ D ON A.YYDM = D.YYDM 
  WHERE 1 = 1 AND A.YYCKDM NOT IN (74, 58, 50) AND A.KCJS > 0 AND A.YYNF = YEAR(CURRENT DATE - 6 MONTH) AND D.GNW = '国外' GROUP BY A.YYDM, A.YYNF 
  UNION ALL 
  SELECT A.YYDM, A.YYNF, VALUE(SUM(A.KCJS), 0) YYKCJS, SUM(A.KCSL) AS KCSL 
  FROM YYZY.T_YYZY_YYKC_NEW AS A INNER JOIN DIM.T_DIM_YYZY_YYZDB AS B ON A.YYDM = B.YYDM AND B.YYMC LIKE '%薄%' AND B.JSRQ >= CURRENT DATE LEFT JOIN CPFNF ON 1 = 1 LEFT JOIN YSSJ D ON D.YYDM = A.YYDM 
  WHERE 1 = 1 AND A.YYCKDM NOT IN (74, 58, 50) AND A.KCJS > 0 AND A.YYNF = YEAR(CURRENT DATE - 6 MONTH) AND D.GNW <> '国外' GROUP BY A.YYDM, A.YYNF, B.YYMC) , CPFKC AS ( 
  SELECT A.YYDM, A.YYNF, VALUE(SUM(YYKCJS), 0) AS YYKCJS, VALUE(SUM(YYKCJS), 0 ) * 200 AS KCSL 
  FROM YYZY.V_YYZY_ZXCPF A LEFT JOIN YSSJ B ON A.YYDM = B.YYDM 
  WHERE 1 = 1 AND A.YYNF = YEAR(CURRENT DATE - 6 MONTH) AND A.YYNF < YEAR(CURRENT DATE) AND B.GNW <> '国外' GROUP BY A.YYDM, A.YYNF) , WJGKC AS ( 
  SELECT YYDM, YYNF, VALUE(SUM(SYKC), 0) AS YYKCJS, VALUE(SUM(SYKC), 0) * 200 AS KCSL 
  FROM YYZY.T_YYZY_YYKC_WJG 
  WHERE YEAR(WJGNF) = YEAR(CURRENT DATE) GROUP BY YYDM, YYNF) , CGJH_TMP AS ( 
  SELECT YYDM, YYNF, VALUE(SUM(YYKCJS), 0) AS YYKCJS, 1 AS YXJ 
  FROM YYZY.V_YYZY_ZXCPF 
  WHERE YYNF >= YEAR(CURRENT DATE) GROUP BY YYDM, YYNF 
  UNION ALL 
  SELECT YYDM, YYNF, VALUE(SUM(CGJHSL), 0) AS YYKCJS, 2 AS YXJ 
  FROM YYZY.V_YYZY_XZCPF_JH 
  WHERE YYNF >= YEAR(CURRENT DATE) GROUP BY YYDM, YYNF) , CGJH AS ( 
  SELECT YYDM, YYNF, YYKCJS, YYKCJS * 200 AS KCSL 
  FROM ( 
  SELECT YYDM, YYNF, YYKCJS, DENSE_RANK() OVER(PARTITION BY YYNF ORDER BY YXJ) AS XH 
  FROM CGJH_TMP) AS TB 
  WHERE XH = 1) , SJ_ALL AS ( 
  SELECT YYDM, YYNF, YYKCJS, KCSL, 1 AS KCLX 
  FROM YYBKC 
  UNION ALL 
  SELECT YYDM, YYNF, YYKCJS, KCSL, 1 AS KCLX 
  FROM CPFKC 
  UNION ALL 
  SELECT YYDM, YYNF, YYKCJS, KCSL, 2 AS KCLX 
  FROM WJGKC 
  UNION ALL 
  SELECT YYDM, YYNF, YYKCJS, KCSL, 3 AS KCLX 
  FROM CGJH) , RESULTS AS ( 
  SELECT A.YYDM, B.YYMC, A.YYNF, DEC(A.YYKCJS, 18, 2) AS YYKCJS, A.KCSL, A.KCLX 
  FROM SJ_ALL AS A LEFT JOIN DIM.T_DIM_YYZY_YYZDB AS B ON A.YYDM = B.YYDM AND A.YYNF = B.YYNF 
  WHERE 1 = 1 AND B.YYMC IS NOT NULL) ,WJGYLKC AS ( 
  SELECT YYCODE,SUM(VALUE(YLJS,0)) AS YLJS,SUM(VALUE(YLWT,0)) AS YLWT 
  FROM YYZY.T_CYWL_V_YLKC_PEIFANG A 
  WHERE (YYCODE,PC,YLLX,RQ) IN (
  SELECT YYCODE,PC,YLLX, MAX(RQ) 
  FROM YYZY.T_CYWL_V_YLKC_PEIFANG GROUP BY YYCODE,PC,YLLX ) AND YLLX IN ('储运内部转仓锁定','发送733锁定（预发送）','发送787锁定（预发送）','发送高扬锁定（预发送）') GROUP BY YYCODE ) ,RSLT AS ( 
  SELECT A.YYDM, A.YYMC, A.YYNF, DEC((INT(A.YYKCJS)+ INT(VALUE(B.YLJS,0))) ,18,2) AS YYKCJS , DEC((INT(A.KCSL)+ INT(VALUE(B.YLWT,0))),18,2 )AS KCSL, KCLX 
  FROM RESULTS A LEFT JOIN WJGYLKC B ON A.YYDM=B.YYCODE 
  WHERE A.KCLX=1 
  UNION ALL 
  SELECT A.YYDM, A.YYMC, A.YYNF, DEC(INT(YYKCJS),18,2) AS YYKCJS , DEC(INT(KCSL),18,2)AS KCSL, KCLX 
  FROM RESULTS A LEFT JOIN WJGYLKC B ON A.YYDM=B.YYCODE 
  WHERE A.KCLX<>1) 
  SELECT YYDM,YYMC,YYNF,YYKCJS,KCSL,KCLX 
  FROM RSLT 
  UNION ALL 
  SELECT A.YYCODE AS YYDM, B.YYMC, B.YYNF, DEC(INT(VALUE(A.YLJS,0)),18,2) AS YYKCJS , DEC(INT(VALUE(A.YLWT,0)),18,2)AS KCSL, 1 AS KCLX 
  FROM WJGYLKC A LEFT JOIN YYZY.T_YYZY_YYZDBMX B ON A.YYCODE=B.YYDM 
  WHERE (A.YYCODE ) NOT IN (
  SELECT YYDM 
  FROM RSLT 
  WHERE KCLX=1)
;
