SET SCHEMA = YYZY;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,KSUSR;

CREATE VIEW YYZY.V_YYZY_YYKC
  ( 
    DQRQ, YYCKDM, CKXZDM, YYCJDM, YYZJDM, YYDM, YYNF, YYBZ, SFCYBJ, KCJS,KCSL 
  )
AS
WITH CYKC_TMP1(HSCD,ARCD,GDCD,CTCD,SBCD,QNT,PKG,YR,WT,UNGETQTY,YYCODE,XH) AS( 
  select HSCD,ARCD,GDCD,CTCD,SBCD,QNT,PKG,YR,WT,UNGETQTY,YYCODE,XH 
  from ( 
  SELECT HSCD ,ARCD,GDCD,CTCD,SBCD, CAST(SUM(QNT) AS DECIMAL(18,2)) as QNT ,PKG, YR,SUM(WT) AS WT, SUM(VALUE(UNGETQTY,0)) as UNGETQTY,YYCODE, ROW_NUMBER()OVER(ORDER BY YYCODE,SUM(QNT) desc,HSCD,CTCD,ARCD) AS XH 
  FROM HDS_YYB1.N_YYB1_TC001 
  WHERE USEFLG='1' GROUP BY CTCD,ARCD,PKG,SBCD,GDCD,YR,HSCD,yycode )a ) ,kczl as ( 
  SELECT SUM(C.QNT) AS KCZL,SUM(C.WT) AS KCSL,SUM(C.UNGETQTY) AS YLZL,C.YYCODE 
  FROM CYKC_TMP1 AS C GROUP BY C.YYCODE) ,CYKC_TMP2 AS ( 
  SELECT A.HSCD, A.ARCD, A.GDCD, A.CTCD, A.SBCD, A.PKG, A.YR, A.WT, A.YYCODE, A.QNT, A.UNGETQTY, A.KCZL, A.YLZL, A.KCLJ, A.KCSL, A.KCSLLJ, A.KCLJ- A.QNT AS KCLJ_LAST, A.KCSLLJ-A.WT AS KCSLLJ_LAST, A.BJMC, A.BJ, A.XH 
  FROM ( 
  select A.HSCD, A.ARCD, A.GDCD, A.CTCD, A.SBCD, A.PKG, A.YR, A.WT, A.YYCODE, A.QNT, A.UNGETQTY, C.KCZL, C.KCSL, C.YLZL, SUM(QNT) OVER( PARTITION BY A.YYCODE ORDER BY A.YYCODE,B.BJ,A.XH ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KCLJ, SUM(WT) OVER(PARTITION BY A.YYCODE ORDER BY A.YYCODE,B.BJ,A.XH ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS KCSLLJ, B.BJ, B.BJMC, A.XH 
  FROM CYKC_TMP1 AS A LEFT JOIN YYZY.V_YYZY_YYCK_SNW_WHB AS B ON A.HSCD=B.YYCKBS LEFT JOIN kczl AS C ON A.YYCODE=C.YYCODE ) AS A ) ,CYKC AS ( 
  SELECT A.HSCD, A.ARCD, A.GDCD, A.CTCD, A.SBCD, A.PKG, A.YR, A.WT AS WT_OLD, A.QNT AS QNT_OLD, CASE WHEN A.KCLJ< A.YLZL AND A.KCLJ_LAST<A.YLZL THEN 0 WHEN A.KCLJ>=A.YLZL AND A.KCLJ_LAST<=A.YLZL THEN A.KCLJ-A.YLZL WHEN A.KCLJ>=A.YLZL AND A.KCLJ_LAST>A.YLZL THEN A.QNT 
  END AS QNT, CASE WHEN A.KCLJ< A.YLZL AND A.KCLJ_LAST<A.YLZL THEN 0 WHEN A.KCLJ>=A.YLZL AND A.KCLJ_LAST<=A.YLZL AND QNT<>0 THEN (WT/QNT)*(A.KCLJ-A.YLZL) - VALUE(((WT/QNT) * 0 ),0) WHEN A.KCLJ>=A.YLZL AND A.KCLJ_LAST>A.YLZL THEN A.WT ELSE 0 
  END AS WT, A.UNGETQTY, A.YYCODE 
  FROM CYKC_TMP2 AS A ) ,RES_TMP AS( 
  SELECT CASE WHEN HOUR(CURRENT TIME) > 8 THEN CURRENT DATE ELSE CURRENT DATE - 1 DAY 
  END AS DQRQ, B.YYCKDM, B.CKXZDM, 0 AS RMCD, 0 AS CLCD, A.YR, A.PKG, ' ' AS SFCYBJ, A.QNT, A.WT, A.YYCODE, A.ARCD, A.GDCD, A.CTCD, A.SBCD 
  FROM CYKC A LEFT JOIN DIM.T_DIM_YYZY_YYCK AS B ON A.HSCD=B.YYCKBS AND CURRENT DATE BETWEEN B.KSRQ AND B.JSRQ 
  UNION ALL 
  SELECT CASE WHEN HOUR(CURRENT TIME) > 8 THEN CURRENT DATE ELSE CURRENT DATE - 1 DAY 
  END AS DQRQ,B.YYCKDM, B.CKXZDM,0 AS RMCD,0 AS CLCD, A.TBYEAR AS YR,A.PKG , ' ' AS SFCYBJ, sum(value(A.KEYONGQNTY ,0))AS QNT,sum(value( A.KEYONGWGHT ,0))AS WT,YYCODE, A.ARCD, A.GDCD, A.CTCD, A.SBCD 
  FROM ( 
  SELECT * 
  FROM HDS_YYB1.N_SYNC_FACTORYSTOCK 
  WHERE SEQNO<>'1334' ) A LEFT JOIN DIM.T_DIM_YYZY_YYCK B ON A.PLCD=B.YYCKBS AND CURRENT DATE BETWEEN B.KSRQ AND B.JSRQ 
  WHERE A.USEFLG='1' GROUP BY B.YYCKDM,B.CKXZDM,A.TBYEAR,A.PKG,YYCODE, A.ARCD, A.GDCD, A.CTCD, A.SBCD ) 
  SELECT A.DQRQ, A.YYCKDM, A.CKXZDM, A.RMCD as YYCJDM, A.CLCD as YYZJDM, B.YYCODE AS YYDM, CAST(A.YR AS INTEGER) as YYNF, CAST(A.PKG AS INTEGER) as YYBZ,A.SFCYBJ, A.QNT as KCJS, A.WT as KCSL 
  FROM RES_TMP AS A LEFT JOIN HDS_YYB1.N_YYB1_TXM003_TOBACCOLEAFINFO AS B ON A.ARCD=B.ARCD AND A.GDCD=B.GDCD AND A.CTCD=B.CTCD AND A.SBCD=B.SBCD AND A.PKG=B.PKCD AND A.YR =B.YR AND B.USEFLG='1'
;
