SET SCHEMA = CYWL;

CREATE PROCEDURE CYWL.P_CYWL_SJJZ ( )
  SPECIFIC SQL130905220049400
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
BEGIN
  
  DECLARE IS_NOT_FOUND INTEGER DEFAULT 0;

  DECLARE CONTINUE HANDLER FOR NOT FOUND
BEGIN 
SET IS_NOT_FOUND=1;
END;

DELETE FROM CYWL.T_MES_DAILY_M;

INSERT INTO CYWL.T_MES_DAILY_M(BILLCODE, ID, GENDATE, SDMAN, REMARK, SDDATE, SDZT,PLCD)
 select BILLCODE,  ID,GENDATE, SDMAN, REMARK, SDDATE, SDZT, PLCD 
 from HDS_CYWL.N_CYWL_MES_DAILY_M;

--2
DELETE FROM CYWL.T_CYWL_MES_DAILY_D;
  INSERT INTO CYWL.T_CYWL_MES_DAILY_D(MVNUM, BILLCODE, YYCODE, PQNTY, PWEIGHT, ID, SDZT, PLCD )
 select MVNUM, BILLCODE, YYCODE, PQNTY, PWEIGHT, ID, SDZT, PLCD 
  from HDS_CYWL.N_CYWL_MES_DAILY_D;

--3
DELETE FROM YYB1.T_YYB1_V_TC001_PEIFANG;

  INSERT INTO YYB1.T_YYB1_V_TC001_PEIFANG(ITMNO, HSCD, RMCD, CLCD, QNT, WT, SPCD, ARCD, GDCD, 
    SBCD, YR, CTCD, PKG, GNDT, WCHR, MEMO, SMKFLG, SDFLG, 
    YCHAR, SMKDT, SINGLEWT, ZLFLG, MGDATE, ISO9000, ZKCD, 
    ZKDATE, ZKADVICE, ZKCHKMAN, CYKDATE, CYKADVICE, CYKCHKMAN, 
    GZKDATE, GZKADVICE, GZKCHKMAN, GZKCHKFLAG, CLCDNO, SMKSTATUS, 
    TI001PRCHKNO, TI009GDSNO, CYKCHKFLAG, TLNTNO, TWM01MNO, 
    TWM02NEWDNO, TTC01TNUM, TI014AWTNO, BUSITYPE, USEFLG, FQNT, 
    FWT, UNGETQTY, YYCODE, BATCHID, REMANT)
    SELECT ITMNO, HSCD, RMCD, CLCD, QNT, WT, SPCD, ARCD, GDCD, 
    SBCD, YR, CTCD, PKG, GNDT, WCHR, MEMO, SMKFLG, SDFLG, 
    YCHAR, SMKDT, SINGLEWT, ZLFLG, MGDATE, ISO9000, ZKCD, 
    ZKDATE, ZKADVICE, ZKCHKMAN, CYKDATE, CYKADVICE, CYKCHKMAN, 
    GZKDATE, GZKADVICE, GZKCHKMAN, GZKCHKFLAG, CLCDNO, SMKSTATUS, 
    TI001PRCHKNO, TI009GDSNO, CYKCHKFLAG, TLNTNO, TWM01MNO, 
    TWM02NEWDNO, TTC01TNUM, TI014AWTNO, BUSITYPE, USEFLG, FQNT, 
    FWT, UNGETQTY, YYCODE, BATCHID, REMANT FROM YYB1.N_YYB1_V_TC001_PEIFANG;

----4
DELETE FROM YYB1.T_YYB1_TXM003_PEIFANG;
 
 INSERT INTO YYB1.T_YYB1_TXM003_PEIFANG(YYCODE, YYNAME, CTCD, SBCD, GDCD, ARCD, PKCD, YR, 
    BATCHID, USEFLG, MEMO, MKMAN, CREATEDATE, MODIFYDATE)
select YYCODE, YYNAME, CTCD, SBCD, GDCD, ARCD, PKCD, YR, 
    BATCHID, USEFLG, MEMO, MKMAN, CREATEDATE, MODIFYDATE
  from YYB1.N_YYB1_TXM003_PEIFANG;

----5
DELETE FROM YYB1.T_YYB1_T_YYZY_YYZDB_DYGX;
INSERT INTO YYB1.T_YYB1_T_YYZY_YYZDB_DYGX(
YYDM_TJ, YYDM_SW, YYNF, YYLBBS, YYCDBS, YYDJBS, YYKBBS, 
    YYPC, ZYBJ, LOAD_TIME
    )
    SELECT 
   YYDM_TJ, YYDM_SW, YYNF, YYLBBS, YYCDBS, YYDJBS, YYKBBS, 
    YYPC, ZYBJ, LOAD_TIME
    FROM YYB1.N_YYB1_T_YYZY_YYZDB_DYGX ;

--6
DELETE FROM CYWL.T_CYWL_TMT037;
INSERT INTO  CYWL.T_CYWL_TMT037(
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, LARCD, SARCD, ARCD
    , GDCD, CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, 
    USEFLG, YQXH, HSCD, JGDT, VTCD, CWDW, YYCODE, BATCHID, 
    XRSJ
    )
    SELECT 
   SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, LARCD, SARCD, ARCD
    , GDCD, CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, 
    USEFLG, YQXH, HSCD, JGDT, VTCD, CWDW, YYCODE, BATCHID, 
    XRSJ
    FROM HDS_CYWL.N_CYWL_TMT037   ;
    

--7
DELETE FROM CYWL.T_CYWL_TMT038;
INSERT INTO  CYWL.T_CYWL_TMT038(
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    TOWN, BUYSTATION
    )
    SELECT 
  SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    TOWN, BUYSTATION
    FROM HDS_CYWL.N_CYWL_TMT038   ;

--8
DELETE FROM CYWL.T_CYWL_TMT039;
INSERT INTO  CYWL.T_CYWL_TMT039(
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, ARCD, BOXNO, GDCD,
    CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, USEFLG, 
    YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, XRSJ
    )
    SELECT 
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, ARCD, BOXNO, GDCD,
    CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, USEFLG, 
    YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, XRSJ
    FROM HDS_CYWL.N_CYWL_TMT039   ;

--9
DELETE FROM CYWL.T_CYWL_TMT040;
INSERT INTO  CYWL.T_CYWL_TMT040(
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    BOXRANGE, BOXBEGIN, BOXEND
    )
    SELECT 
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    BOXRANGE, BOXBEGIN, BOXEND
    FROM HDS_CYWL.N_CYWL_TMT040   ;

--10
DELETE FROM CYWL.T_CYWL_TMT046;
INSERT INTO  CYWL.T_CYWL_TMT046(
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, LARCD, SARCD, ARCD
    , GDCD, CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, 
    USEFLG, YQXH, HSCD, JGDT, VTCD, CWDW, YYCODE, BATCHID, 
    XRSJ
    )
    SELECT 
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, LARCD, SARCD, ARCD
    , GDCD, CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, 
    USEFLG, YQXH, HSCD, JGDT, VTCD, CWDW, YYCODE, BATCHID, 
    XRSJ
    FROM HDS_CYWL.N_CYWL_TMT046   ;
    
    
----11 CYWL.T_CYWL_TMT050
DELETE FROM CYWL.T_CYWL_TMT050;
  INSERT INTO CYWL.T_CYWL_TMT050( SEQNO, TGCD, TGMAK, TGVAL, USEFLG, SBH, YPXH, JYRBZ, TOWN, BUYSTATION)
  select SEQNO, TGCD, TGMAK, TGVAL, USEFLG, SBH, YPXH, JYRBZ, 
    TOWN, BUYSTATION
  from HDS_CYWL.N_CYWL_TMT050;


----12 CYWL.T_CYWL_TMT052
DELETE FROM CYWL.T_CYWL_TMT052;
INSERT INTO CYWL.T_CYWL_TMT052(SEQNO, PLCD, CHKMAN, CHKDT, LARCD, SARCD, ARCD, GDCD, 
    CTCD, SBCD, VTCD, YR, MAKCD, MAKDT, REMARK, SDFLG, 
    USEFLG, YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, XRSJ)

select SEQNO, PLCD, CHKMAN, CHKDT, LARCD, SARCD, ARCD, GDCD, 
    CTCD, SBCD, VTCD, YR, MAKCD, MAKDT, REMARK, SDFLG, 
    USEFLG, YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, XRSJ
  from HDS_CYWL.N_CYWL_TMT052 ;


----13
DELETE FROM CYWL.T_CYWL_TMT053;
INSERT INTO  CYWL.T_CYWL_TMT053(
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    TOWN, BUYSTATION
    )
    SELECT 
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    TOWN, BUYSTATION
    FROM HDS_CYWL.N_CYWL_TMT053   ;
    
------    14
DELETE FROM CYWL.T_CYWL_TMT057_LSBYMAIN;

INSERT INTO  CYWL.T_CYWL_TMT057_LSBYMAIN(
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, LARCD, SARCD, ARCD
    , GDCD, CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, 
    SDFLG, USEFLG, YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, 
    XRSJ
    )
    SELECT 
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, LARCD, SARCD, ARCD
    , GDCD, CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, 
    SDFLG, USEFLG, YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, 
    XRSJ
    FROM HDS_CYWL.N_CYWL_TMT057_LSBYMAIN   ;
    
    ---15
    DELETE FROM CYWL.T_CYWL_TMT058_LSBYCHILD;
    INSERT INTO  CYWL.T_CYWL_TMT058_LSBYCHILD(
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    TOWN, BUYSTATION
    )
    SELECT 
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    TOWN, BUYSTATION
    FROM HDS_CYWL.N_CYWL_TMT058_LSBYCHILD   ;
    
    --16
    DELETE FROM CYWL.T_CYWL_TMT060_LSPYMAIN;
        INSERT INTO  CYWL.T_CYWL_TMT060_LSPYMAIN(
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, ARCD, BOXNO, GDCD,
    CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, USEFLG, 
    YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, XRSJ
    )
    SELECT 
SEQNO, PLCD, CHKMAN, CHKDT, WKORDER, ARCD, BOXNO, GDCD,
    CTCD, SBCD, YR, MAKCD, MAKDT, REMARK, SDFLG, USEFLG, 
    YQXH, HSCD, JGDT, CWDW, YYCODE, BATCHID, XRSJ
    FROM HDS_CYWL.N_CYWL_TMT060_LSPYMAIN   ;
    
----    --17
    DELETE FROM  CYWL.T_CYWL_TMT061_LSPYCHILD;
            INSERT INTO  CYWL.T_CYWL_TMT061_LSPYCHILD(
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    BOXRANGE, BOXBEGIN, BOXEND
    )
    SELECT 
SEQNO, TGCD, TGMAK, TGVAL, SBH, USEFLG, YPXH, JYRBZ, 
    BOXRANGE, BOXBEGIN, BOXEND
    FROM HDS_CYWL.N_CYWL_TMT061_LSPYCHILD   ;
    
    --18
    DELETE FROM CYWL.T_CYWL_TQM180_QAMAIN;
INSERT INTO  CYWL.T_CYWL_TQM180_QAMAIN(
QAID, ASTOCKID, CTCD, SBCD, GDCD, ARCD, PKCD, YR, PC,
    HSID, BUID, RMID, CLID, DVAL, XRSJ, QATYPE
    )
    SELECT 
QAID, ASTOCKID, CTCD, SBCD, GDCD, ARCD, PKCD, YR, PC,
    HSID, BUID, RMID, CLID, DVAL, XRSJ, QATYPE
    FROM HDS_CYWL.N_CYWL_TQM180_QAMAIN   ;
    
    ---19
    DELETE FROM CYWL.T_CYWL_TQM181_QADETAIL;
INSERT INTO  CYWL.T_CYWL_TQM181_QADETAIL(
 AQAID, QAID, CNO, VAL1, VAL2, VAL3, VAL4, VAL5, VAL6,
    VAL7
    )
    SELECT 
 AQAID, QAID, CNO, VAL1, VAL2, VAL3, VAL4, VAL5, VAL6,
    VAL7
    FROM HDS_CYWL.N_CYWL_TQM181_QADETAIL   ;

---20
DELETE FROM  CYWL.T_YYZY_JHPT_XTLJRZB;
INSERT INTO  CYWL.T_YYZY_JHPT_XTLJRZB(
 LSM, XTJC, CZSJ, CZLX, CZBM, LJYH, BZ
    )
    SELECT 
 LSM, XTJC, CZSJ, CZLX, CZBM, LJYH, BZ
    FROM HDS_CYWL.N_CYWL_T_YYZY_JHPT_XTLJRZB;
    
END;
