SET SCHEMA YYZYUSR ;
SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,YYZYUSR;

CREATE PROCEDURE JYHSF.P_JYHSF_SJJZ ( ) 
  SPECIFIC JYHSF.SQL130820211017400
  LANGUAGE SQL
  NOT DETERMINISTIC
  CALLED ON NULL INPUT
  EXTERNAL ACTION
  OLD SAVEPOINT LEVEL
  MODIFIES SQL DATA
  INHERIT SPECIAL REGISTERS
  BEGIN
  
  --日生产计划取整(2013-08-20注释，将此过程放于外层)
  --CALL YYZY.P_YYZY_RSCJHB_WHB_PCQZ();
  --日生产计划表
  DELETE FROM  JYHSF.T_JYHSF_RSCJHB;
    INSERT INTO  JYHSF.T_JYHSF_RSCJHB( PFPHDM, KSRQ, JSRQ, JHCL_AVG, JHPC_AVG, BBRQ)
     SELECT PFPHDM, KSRQ, JSRQ, JHCL_AVG, JHPC_AVG, BBRQ
    FROM YYZY.T_YYZY_RSCJHB_WHB;
  
  --角色信息表
  DELETE FROM JYHSF.T_JYHSF_JSXX;
  INSERT INTO JYHSF.T_JYHSF_JSXX ( PFPHDM, JSDM, KSRQ, JSRQ, DPXS)
  SELECT PFPHDM, JSDM, KSRQ, JSRQ, DPXS
  FROM YYZY.T_YYZY_JSTZ_WHB  WHERE ZYBJ='1';
  
  --库存及烟碱信息
  DELETE FROM JYHSF.T_JYHSF_KCJYJXX;
  INSERT INTO JYHSF.T_JYHSF_KCJYJXX (YYDM, FKPC, YJ, KCXS)
  SELECT A.YYDM, '1' AS FKPC, CASE WHEN C.ZYJ IS NULL THEN  D.ZYJ ELSE C.ZYJ END AS YJ,A.YYKCJS
  FROM YYZY.V_YYZY_YYKC_WHB A
  LEFT JOIN  YYZY.T_YYZY_YYZDBMX B ON A.YYDM=B.YYDM
  LEFT JOIN (SELECT DJBS,LBBS,KBBS,CDBS,YYNF,AVG(ZYJ) ZYJ   
    FROM YYZY.T_YYZY_HXJC_KC_HZ 
  GROUP BY DJBS,LBBS,KBBS,CDBS,YYNF ) C ON C.DJBS=B.YYDJBS AND LEFT(C.LBBS,1)= LEFT(B.YYLBBS,1) AND C.CDBS=B.YYCDBS AND C.KBBS=B.YYKBBS AND B.YYNF=C.YYNF 
  LEFT JOIN (SELECT DJBS,LBBS,KBBS,CDBS,YYNF,AVG(ZYJ) ZYJ   
  FROM  YYZY.T_YYZY_HXJC_CY_HZ 
  GROUP BY DJBS,LBBS,KBBS,CDBS,YYNF ) D ON  D.DJBS=B.YYDJBS AND LEFT(D.LBBS,1)= LEFT(B.YYLBBS,1) AND D.CDBS=B.YYCDBS AND D.KBBS=B.YYKBBS AND B.YYNF=D.YYNF;
  INSERT INTO JYHSF.T_JYHSF_KCJYJXX(YYDM,FKPC,KCXS) VALUES('0','1',99999999);
  
  --牌号顺序更新
  INSERT INTO JYHSF.T_JYHSF_PFPXB(PFPHDM, PFPHMC, PFPHSX)
   SELECT A.PFPHDM, A.PFPHMC, ROW_NUMBER()OVER()*10+XH AS PX
  FROM DIM.T_DIM_YYZY_PFPH AS A
  LEFT JOIN (SELECT MAX(PFPHSX) AS XH FROM JYHSF.T_JYHSF_PFPXB)
     ON 1=1
   WHERE SCCJDM IN (0,1,2)
   AND PFPHDM IN (SELECT DISTINCT PFPHDM FROM JYHSF.T_JYHSF_ZXPF WHERE PFPHDM NOT IN (SELECT PFPHDM FROM JYHSF.T_JYHSF_PFPXB))
   AND PFPHDM NOT IN (SELECT PFPHDM FROM YYZY.T_YYZY_PFPH_CFG WHERE GPBJ='1' AND JSBJ='0')
   ORDER BY PFPHDM;

END;

COMMENT ON PROCEDURE JYHSF.P_JYHSF_SJJZ ( ) IS '均匀化算法_数据加载';
