SET SCHEMA = YYZY;

CREATE PROCEDURE YYZY.P_YYZY_CBGZ_JZ ( )
  SPECIFIC SQL110510162625600
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
/*
  描述： 1、将存在于 T_YYZY_YYCBGZ 中而不存在于 T_YYZY_SYSDYDM 中的数据删除
         2、将存在于 T_YYZY_SYSDYDM 中而不存在于 T_YYZY_YYCBGZ 中的
            非“把烟,原烟”数据插入 T_YYZY_YYCBGZ中
  */
BEGIN
    --定义系统变量
  DECLARE SQLCODE INT DEFAULT 0;
  DECLARE SQLSTATE CHAR(5) DEFAULT '00000';
  DECLARE ERR_MEG  VARCHAR(5000) DEFAULT '';
  
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION
    BEGIN
      set ERR_MEG = '系统错误：SQLCODE='||rtrim(char(SQLCODE))||',SQLSTATE='||SQLSTATE||';  '; 
    END;
    
  --删除表 YYZY.T_YYZY_YYCBGZ 中冗余的数据
  DELETE FROM YYZY.T_YYZY_YYCBGZ 
    WHERE YYDM IN( 
        --选择冗余数据
        SELECT YYDM
          FROM YYZY.T_YYZY_YYCBGZ
          WHERE YYDM NOT IN(
                      SELECT YYDM 
                        FROM YYZY.T_YYZY_SYSDYDM)
      );
              
  --插入新的数据
  INSERT INTO YYZY.T_YYZY_YYCBGZ(YYDM,CBGZZXZ,CBGZSX,CBGZXX,BBH,BBRQ)
      SELECT YYDM ,36 AS CBGZZXZ, 1 AS CBGZSX, -1 AS CBGZXX, 
            1 AS BBH, CURRENT DATE AS BBRQ
        FROM YYZY.T_YYZY_SYSDYDM
        WHERE YYDM NOT IN(
                    SELECT YYDM 
                      FROM YYZY.T_YYZY_YYCBGZ)
            AND YYKBDM NOT IN(1,2);
END;

COMMENT ON PROCEDURE YYZY.P_YYZY_CBGZ_JZ(  ) IS '烟叶储备规则数据加载';
