SET SCHEMA = YYZY;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,ETLUSR;

CREATE VIEW YYZY.V_YYZY_ZXPFZLYY
    ( PFPHDM, JSDM, YYDM, YYNF )
AS
WITH ZLYY_ZXPF AS ( 
  SELECT PFPHDM, JSDM, YYDM, YYNF, KSRQ, JSRQ,TDSX AS ZXSX,ZPFBJ 
  FROM YYZY.T_YYZY_ZXPF_WHB 
  WHERE YYDM<>'0' 
  UNION ALL 
  SELECT PFPHDM, JSDM, YYDM, YYNF, KSRQ, JSRQ, ZXSX ,ZPFBJ 
  FROM YYZY.T_YYZY_ZXPF_LSB 
  WHERE YYDM<>'0' AND JSRQ>(CURRENT DATE - 1 YEAR) ),ZLYY_FX AS ( 
  SELECT PFPHDM, JSDM, YYDM, YYNF, KSRQ, JSRQ, ZXSX ,ZPFBJ, ROWNUMBER()OVER( PARTITION BY PFPHDM,JSDM ORDER BY ZPFBJ DESC,JSRQ DESC,KSRQ DESC,ZXSX DESC) AS XH 
  FROM ZLYY_ZXPF ) 
  SELECT PFPHDM,JSDM,YYDM,YYNF 
  FROM ZLYY_FX 
  WHERE XH=1
;
