drop FUNCTION MATH.F_LCM;

CREATE FUNCTION MATH.F_LCM( 
  VAL1 INTEGER, 
  VAL2 INTEGER 
) 
  RETURNS DOUBLE
  SPECIFIC math.F_LCM 
  LANGUAGE SQL
  NOT DETERMINISTIC
  NO EXTERNAL ACTION
  CONTAINS SQL
RETURN 
  VAL1 * VAL2 / MATH.F_GCD(VAL1,VAL2)
;