--DROP TABLE YYZY.T_YYZY_SJTL_ZDQRSJ;
CREATE TABLE YYZY.T_YYZY_SJTL_ZDQRSJ( 
  GXSJ DATE, 
  PFPHDM INTEGER, 
  yqrsj DATE 
) IN TS_REG_16K;

ALTER TABLE YYZY.T_YYZY_SJTL_ZDQRSJ
  LOCKSIZE ROW
  APPEND OFF
  NOT VOLATILE
  LOG INDEX BUILD NULL;

COMMENT ON TABLE YYZY.T_YYZY_SJTL_ZDQRSJ
  IS '实际投料数据已确认日期表';

COMMENT ON YYZY.T_YYZY_SJTL_ZDQRSJ(
  GXSJ IS '更新时间',
  PFPHDM IS '配方牌号代码',
  yqrsj IS  '已确认日期'
);