SET SCHEMA = APP_YYB;

CREATE PROCEDURE APP_YYB.P_YYZY_JHJZ_YEAR ( )
  SPECIFIC SQL070907033705100
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
--存储过程
  BEGIN 
    --定义系统变量 
    DECLARE SQLSTATE CHAR(5); 
    DECLARE SQLCODE INTEGER;  
    
    --定义
    DECLARE STMT VARCHAR(4000);
    DECLARE STMT2 VARCHAR(4000); 
    DECLARE STMT3 VARCHAR(4000);
    DECLARE TYPE CHAR(1); 
    DECLARE COUNT INTEGER DEFAULT 0;
    DECLARE ISEXIST INTEGER DEFAULT 0;
    DECLARE i ,I_LSBH,max_bbh,month_1,month_2 INTEGER DEFAULT 0;
    DECLARE STRCNT VARCHAR(100) DEFAULT '';
     DECLARE ERR_MSG VARCHAR(1000) DEFAULT ''; 
--    DECLARE RUNSTATUS INTEGER;
    DECLARE AT_END SMALLINT DEFAULT 0;

    --定义动态游标 
    DECLARE c1 CURSOR FOR s1;
    DECLARE c2 CURSOR FOR s2;
    
    --定义异常处理
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION   
      SET ERR_MSG = '系统错误：SQLCODE='||RTRIM(CHAR(SQLCODE))||',SQLSTATE='||SQLSTATE||';  ';
--插入初始记录      
    insert into  YYZY.T_YYZY_JZ_RZ  (BZ, MBB, JZSJ, SFCG)
    values
    ('','YYZY.T_YYZY_NSCJH',current timestamp,0);
    select MAX(LSBH) INTO I_LSBH FROM YYZY.T_YYZY_JZ_RZ WHERE MBB='YYZY.T_YYZY_NSCJH';
    delete from YYZY.T_YYZY_TMP_NSCJH;
    insert into YYZY.T_YYZY_TMP_NSCJH (NSCJHDM, JHNF, JHYF, YHBS, CJDM,   JHCL, ZYBJ,   BBH, BBRQ, KSRQ, JSRQ, BRIEFNM, PZMC, PZDM, PPDM)
    WITH T1 AS(
SELECT Y.PLANID,
       Y.TOBACCOID,
       Y.CMONTH,
       Y.CYEAR, 
       Y.QUANTITY,
       Y.N_VERSION,
       SUBSTR(Y.C_CREATETIME, 1, 4) || '-' || SUBSTR(Y.C_CREATETIME, 5, 2) || '-' ||
       SUBSTR(Y.C_CREATETIME, 7, 2) BBRQ
  FROM HDS_CXQJ.N_CXQJ_O_REGION_YEARPLAN AS Y
 WHERE C_CREATETIME IS NOT NULL
)
,T2 AS (
SELECT SUM(T.QUANTITY) AS QUANTITY,
       T.CMONTH,
       T.N_VERSION,
       T.TOBACCOID,
       CYEAR,
       BBRQ
  FROM T1 AS T
 GROUP BY T.CMONTH, T.N_VERSION, T.TOBACCOID, CYEAR, BBRQ
 ORDER BY T.CMONTH, T.TOBACCOID
)
,T3 AS (
SELECT DISTINCT Y.TOBACCOID,C_FACTORYID
  FROM HDS_CXQJ.N_CXQJ_O_REGION_YEARPLAN AS Y
),T4 AS (
SELECT DISTINCT T.TOBACCOID, max(F.FACTORYNAME) FACTORYNAME
  FROM T3 AS T 
  LEFT JOIN (SELECT DISTINCT FACTORYID, FACTORYNAME
             FROM HDS_CXQJ.N_CXQJ_O_FACTORYINFO) AS F 
             ON F.FACTORYID = T.C_FACTORYID
  group by T.TOBACCOID)
,tmp_tcm21 as 
        (
        SELECT b.STANDARDID,  C.BARCODE2 ,FORMULAID, BRIEFNM
          FROM (SELECT TOBACCOID_M, MIN(TOBACCOID_D) TOBACCOID_D
                  FROM (SELECT TOBACCOID_M,
                               TOBACCOID_D,
                               INT(C_YEAR) * 100 + INT(C_MONTH),
                               DENSE_RANK() OVER(PARTITION BY TOBACCOID_M ORDER BY INT(C_YEAR) * 100 + INT(C_MONTH) DESC, TOBACCOID_D DESC) AS XH
                        
                          FROM HDS_CXQJ.N_CXQJ_O_TOBACCO_KIND_H
                         WHERE TOBACCOID_D NOT LIKE '%@%'
                         ORDER BY TOBACCOID_M, INT(C_YEAR) * 100 + INT(C_MONTH), TOBACCOID_D) AA
                 WHERE XH = 1
                 GROUP BY TOBACCOID_M
          ) A,
               (SELECT DISTINCT STANDARDID, BARCODE2
                  FROM HDS_TF01.N_TF01_TCM21
                 WHERE (BARCODE2 IS NULL OR BARCODE2 = '')) B,
               (SELECT DISTINCT STANDARDID, BARCODE2,FORMULAID, BRIEFNM
                  FROM HDS_TF01.N_TF01_TCM21
                 WHERE (BARCODE2 IS NOT NULL AND BARCODE2 <> '')) C
         WHERE A.TOBACCOID_M = B.STANDARDID
           AND TOBACCOID_D = C.STANDARDID
           
           union 
           SELECT DISTINCT STANDARDID, BARCODE2,FORMULAID, BRIEFNM
                  FROM HDS_TF01.N_TF01_TCM21
                 WHERE (BARCODE2 IS NOT NULL AND BARCODE2 <> '' )
        )
--select * from t4 order by 1
SELECT 
(SELECT VALUE(MAX(NSCJHDM), 0) FROM YYZY.T_YYZY_NSCJH) + ROWNUMBER() OVER(),
       INTEGER(CYEAR),
       INTEGER(CMONTH),
       D.FORMULAID,
       (CASE
         WHEN FACTORYNAME = '上海卷烟厂' THEN
          1
         ELSE
          2
       END) CJDM,
       QUANTITY,
       '1' ZYBJ,
       N_VERSION,
       BBRQ,
       '1980-01-01' AS KSRQ,
       '3000-12-31' AS JSRQ,
       BRIEFNM,
       JTPZMC,
       JTPZDM,
       PPDM   
  FROM T2 AS T
  LEFT JOIN tmp_tcm21 AS D ON D.STANDARDID = T.TOBACCOID
  LEFT JOIN T4 AS F ON F.TOBACCOID = T.TOBACCOID
  LEFT JOIN (SELECT DISTINCT THTXBS, JTPZMC, JTPZDM, PPDM
  FROM (SELECT THTXBS,
               JTPZMC,
               JTPZDM,
               PPDM,
               DENSE_RANK() OVER(PARTITION BY THTXBS ORDER BY JTPZDM DESC) AS XH
          FROM ODS_DM.N_DM_JTPZ) A
 WHERE XH = 1) AS J ON D.BARCODE2 = J.THTXBS;

delete from YYZY.T_YYZY_NSCJH;
insert into  YYZY.T_YYZY_NSCJH
    ( NSCJHDM, JHNF, JHYF, YHBS, CJDM,   JHCL, ZYBJ,   BBH, BBRQ, KSRQ, JSRQ, BRIEFNM, PZMC, PZDM, PPDM)
select  NSCJHDM, JHNF, JHYF, YHBS, CJDM,   JHCL, ZYBJ,   BBH, BBRQ, KSRQ, JSRQ, BRIEFNM, PZMC, PZDM, PPDM from YYZY.T_YYZY_TMP_NSCJH;
    UPDATE YYZY.T_YYZY_JZ_RZ SET 
    BZ='当日加载成功',sfcg=1 
    WHERE LSBH=I_LSBH;

    return 1;

END;

COMMENT ON PROCEDURE APP_YYB.P_YYZY_JHJZ_YEAR(  ) IS '每日加载年计划，更更新工作日表，并记录入日志';
