SET SCHEMA = APP_YYB;

CREATE PROCEDURE APP_YYB.P_YYZY_JHJZ_MONTH ( )
  SPECIFIC SQL070828044719100
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
--存储过程
  BEGIN 
    --定义系统变量 
    DECLARE SQLSTATE CHAR(5); 
    DECLARE SQLCODE INTEGER;  
     
    --定义
    DECLARE STMT VARCHAR(4000);
    DECLARE STMT2 VARCHAR(4000); 
    DECLARE STMT3 VARCHAR(4000);
    DECLARE TYPE CHAR(1); 
    DECLARE COUNT INTEGER DEFAULT 0;
    DECLARE ISEXIST INTEGER DEFAULT 0;
    DECLARE i ,I_LSBH,max_bbh,month_1,month_2 INTEGER DEFAULT 0;
    DECLARE STRCNT VARCHAR(100) DEFAULT '';
     DECLARE ERR_MSG VARCHAR(1000) DEFAULT ''; 
--    DECLARE RUNSTATUS INTEGER;
    DECLARE AT_END SMALLINT DEFAULT 0;

    --定义动态游标 
    DECLARE c1 CURSOR FOR s1;
    DECLARE c2 CURSOR FOR s2;
    
    --定义异常处理
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION   
      SET ERR_MSG = '系统错误：SQLCODE='||RTRIM(CHAR(SQLCODE))||',SQLSTATE='||SQLSTATE||';  ';
    --插入初始记录    
    insert into  YYZY.T_YYZY_JZ_RZ  (BZ, MBB, JZSJ, SFCG)
    values
    ('','YYZY.T_YYZY_YSCJH',current timestamp,0);
    select MAX(LSBH) INTO I_LSBH FROM YYZY.T_YYZY_JZ_RZ WHERE MBB='YYZY.T_YYZY_YSCJH';
    SELECT COUNT(1) INTO I FROM (
    SELECT  substr(T.C_CREATETIME,1,4)||'-'||substr(T.C_CREATETIME,5,2)||'-'||substr(T.C_CREATETIME,7,2)
    FROM HDS_CXQJ.N_CXQJ_O_PRODPLAN T
    EXCEPT
    SELECT BBRQ FROM YYZY.T_YYZY_YSCJH        
    
    ) AA;
    IF I=0 THEN RETURN; END IF;
    
    delete from YYZY.T_YYZY_TMP_YSCJH;
    
insert into YYZY.T_YYZY_TMP_YSCJH
( YSCJHDM, JHNF, JHYF, YHBS, CJDM, BRIEFNM, JHCL, 
  ZYBJ,  BBH, BBRQ, KSRQ, JSRQ,pzmc,pzdm,ppdm )
WITH T1 AS (
  SELECT Y.SYSTEMID, Y.TOBACCOID, Y.C_MONTH, Y.C_YEAR , Y.QUANTITY,Y.FACTORYID, Y.C_CREATETIME,y.N_VERSION
  FROM HDS_CXQJ.N_CXQJ_O_PRODPLAN AS Y
)
,T2 AS (
  SELECT CAST(T.C_YEAR AS INTEGER) AS JHNF,CAST(T.C_MONTH AS INTEGER) AS JHYF,
      D.FORMULAID,D.BRIEFNM,T.QUANTITY,
      substr(T.C_CREATETIME,1,4)||'-'||substr(T.C_CREATETIME,5,2)||'-'||substr(T.C_CREATETIME,7,2) AS BBRQ,
      T.TOBACCOID,F.FACTORYNAME,'1' AS ZYBJ,N_VERSION AS BBH,'1980-01-01'AS KSRQ,'3000-12-31'AS JSRQ
  FROM T1 AS T
  LEFT JOIN (
    SELECT DISTINCT STANDARDID,BRIEFNM,FORMULAID 
    FROM HDS_CXQJ.N_TF01_TCM21
    where useflg='Y'
  ) AS D 
    ON  D.STANDARDID=T.TOBACCOID
  LEFT JOIN (
    SELECT DISTINCT FACTORYID, FACTORYNAME 
    FROM HDS_CXQJ.N_CXQJ_O_FACTORYINFO
  ) AS F 
    ON  F.FACTORYID=T.FACTORYID
)
,T3 AS(
 SELECT DISTINCT TOBACCOID,BRIEFNM
   FROM T2 AS T
   ORDER BY TOBACCOID
)
,T11 AS (
  SELECT Y.SYSTEMID, Y.TOBACCOID, Y.C_MONTH, Y.C_YEAR , Y.QUANTITY,Y.FACTORYID, Y.C_CREATETIME,y.N_VERSION
  FROM HDS_CXQJ.N_CXQJ_O_PRODPLAN AS Y
)
,T21 AS (
  SELECT CAST(T.C_YEAR AS INTEGER) AS JHNF,CAST(T.C_MONTH AS INTEGER) AS JHYF,D.FORMULAID,D.BRIEFNM,T.QUANTITY,
       substr(T.C_CREATETIME,1,4)||'-'||substr(T.C_CREATETIME,5,2)||'-'||substr(T.C_CREATETIME,7,2) AS BBRQ,
       T.TOBACCOID,F.FACTORYNAME,'1' AS ZYBJ,N_VERSION AS BBH,'1980-01-01'AS KSRQ,'3000-12-31'AS JSRQ
  FROM T11 AS T
  LEFT JOIN (
    SELECT DISTINCT STANDARDID,BRIEFNM,FORMULAID
    FROM HDS_CXQJ.N_TF01_TCM21
    where useflg='Y'
  ) AS D 
    ON  D.STANDARDID=T.TOBACCOID
  LEFT JOIN (
    SELECT DISTINCT FACTORYID, FACTORYNAME 
    FROM HDS_CXQJ.N_CXQJ_O_FACTORYINFO
  ) AS F 
    ON  F.FACTORYID=T.FACTORYID
)
,T31 AS(
  SELECT DISTINCT TOBACCOID,BRIEFNM
  FROM T21 AS T
  ORDER BY TOBACCOID
)
,hj as (  
  SELECT T.JHNF,T.JHYF,T.FORMULAID,1 AS CJDM,T.BRIEFNM,T.QUANTITY,T.ZYBJ,T.BBH,T.BBRQ,T.KSRQ,T.JSRQ,TOBACCOID
  FROM T2 AS T
  WHERE TOBACCOID<>'CHN31010001F000195000001000' AND T.FACTORYNAME='上海卷烟厂'
  UNION all
  SELECT T.JHNF,T.JHYF,T.FORMULAID,2 AS CJDM,T.BRIEFNM,T.QUANTITY,T.ZYBJ,T.BBH,T.BBRQ,T.KSRQ,T.JSRQ,TOBACCOID
  FROM T2 AS T
  WHERE (TOBACCOID<>'CHN31010001F000195000001000' AND T.FACTORYNAME='上海高扬国际烟草有限公司')
    and (tobaccoid<>'CHN31010001D000254000003000' and T.FACTORYNAME='上海高扬国际烟草有限公司')
  UNION all
  SELECT T.JHNF,T.JHYF,T.FORMULAID,1 AS CJDM,T.BRIEFNM,T.QUANTITY,T.ZYBJ,T.BBH,T.BBRQ,T.KSRQ,T.JSRQ,TOBACCOID
  FROM T21 AS T
  WHERE TOBACCOID='CHN31010001F000195000001000' AND T.FACTORYNAME='上海卷烟厂' AND BRIEFNM<>'84硬盒中华(15mg)'
  union all
  select T.JHNF,T.JHYF,T.FORMULAID,1 AS CJDM,T.BRIEFNM,T.QUANTITY,T.ZYBJ,T.BBH,T.BBRQ,T.KSRQ,T.JSRQ,TOBACCOID
  FROM T21 AS T 
  where (tobaccoid='CHN31010001D000254000003000' and T.FACTORYNAME='上海高扬国际烟草有限公司')
  UNION all
  SELECT T.JHNF,T.JHYF,T.FORMULAID,2 AS CJDM,T.BRIEFNM,T.QUANTITY,T.ZYBJ,T.BBH,T.BBRQ,T.KSRQ,T.JSRQ,TOBACCOID
  FROM T21 AS T
  WHERE TOBACCOID='CHN31010001F000195000001000' AND T.FACTORYNAME='上海高扬国际烟草有限公司' AND BRIEFNM<>'84硬盒中华(15mg)'
)
select (SELECT value(MAX(YSCJHDM),0) FROM YYZY.T_YYZY_YSCJH) + ROWNUMBER() OVER() xh,
    jhnf,jhyf,formulaid as yhbs,cjdm,briefnm,quantity,zybj,bbh,bbrq,ksrq,jsrq,jtpzmc,jtpzdm,ppdm
from hj as T
LEFT JOIN (
  SELECT b.STANDARDID,  C.BARCODE2
  FROM (
    SELECT TOBACCOID_M, MIN(TOBACCOID_D) TOBACCOID_D
    FROM HDS_CXQJ.N_CXQJ_O_TOBACCO_KIND_H
    WHERE TOBACCOID_D not like '%@%' 
      and INT(C_YEAR) * 100 + INT(C_MONTH) =(SELECT MAX(INT(C_YEAR) * 100 + INT(C_MONTH))
                  FROM HDS_CXQJ.N_CXQJ_O_TOBACCO_KIND_H)
    GROUP BY TOBACCOID_M
  ) A,
  (
    SELECT DISTINCT STANDARDID, BARCODE2
    FROM HDS_TF01.N_TF01_TCM21
    WHERE (BARCODE2 IS NULL OR BARCODE2 = '')
  ) B,
  (
    SELECT DISTINCT STANDARDID, BARCODE2
    FROM HDS_TF01.N_TF01_TCM21
    WHERE (BARCODE2 IS NOT NULL AND BARCODE2 <> '')
  ) C
  WHERE A.TOBACCOID_M = B.STANDARDID
    AND TOBACCOID_D = C.STANDARDID
  union 
  SELECT DISTINCT STANDARDID, BARCODE2 
  FROM HDS_TF01.N_TF01_TCM21
  WHERE (BARCODE2 IS NOT NULL AND BARCODE2 <> '')
) AS D 
  ON  D.STANDARDID=T.TOBACCOID
LEFT JOIN (
  SELECT DISTINCT THTXBS, JTPZMC,jtpzdm,ppdm 
  FROM ODS_DM.N_DM_JTPZ 
  where gcdm in (49,50) 
    and  jsrq>current date
    and  jtpzmc not like '%牡丹(11mg%' 
    and jtpzmc not like '%红双喜(11mg%' 
    and jtpzmc <>'84硬盒红双喜(15mg精品)'  
  order by thtxbs
) AS J 
  ON d.BARCODE2 = J.THTXBS
;
    UPDATE YYZY.T_YYZY_JZ_RZ SET 
    BZ='当日加载n成功',sfcg=2
    WHERE LSBH=I_LSBH;
    
    SELECT COUNT(1) INTO I FROM YYZY.T_YYZY_TMP_YSCJH ;        
    IF I=0 THEN RETURN 0; END IF;
    delete from YYZY.T_YYZY_YSCJH;
    insert into YYZY.T_YYZY_YSCJH
( YSCJHDM, JHNF, JHYF, YHBS, CJDM, BRIEFNM, JHCL, 
  ZYBJ,  BBH, BBRQ, KSRQ, JSRQ,pzmc,pzdm,ppdm )
  select YSCJHDM, JHNF, JHYF, YHBS, CJDM, BRIEFNM, JHCL, 
  ZYBJ,  BBH, BBRQ, KSRQ, JSRQ,pzmc,pzdm,ppdm from YYZY.T_YYZY_TMP_YSCJH;
    UPDATE YYZY.T_YYZY_JZ_RZ SET 
    BZ='当日加载成功',sfcg=1
    WHERE LSBH=I_LSBH;
  return 1;

END;

COMMENT ON PROCEDURE APP_YYB.P_YYZY_JHJZ_MONTH(  ) IS '每日加载月生产计划，并记录入日志';
