--drop PROCEDURE YYZY.P_YYZY_LSPF_SJDHB; 

SET SCHEMA = ETLUSR;
SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,ETLUSR;

CREATE PROCEDURE YYZY.P_YYZY_LSPF_SJDHB 
( 
)
  SPECIFIC PROC_YYZY_LSPF_SJDHB
  LANGUAGE SQL
  NOT DETERMINISTIC
  NO EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
LB_MAIN:
BEGIN ATOMIC
  /* DECLARE SYSTEM VARIABLES */
  DECLARE SQLSTATE CHAR(5); 
  DECLARE SQLCODE INTEGER; 
  DECLARE V_SQLSTATE CHAR(5); 
  DECLARE I_SQLCODE INTEGER; 
  DECLARE SQL_CUR_AT_END INTEGER; 
  DECLARE SQL_STMT VARCHAR(2000); 
  /* DECLARE USER-DEFINED VARIABLES */ 
  
  /* DECLARE STATIC CURSOR */
  -- DECLARE C1 CURSOR /*WITH RETURN*/ FOR
  --   SELECT DISTINCT NAME, CREATOR, TYPE
  --   FROM SYSIBM.SYSTABLES
  --   ORDER BY TYPE,CREATOR,NAME
  -- ;
  /* DECLARE DYNAMIC CURSOR */
  -- DECLARE C2 CURSOR FOR S2;
  /* DECLARE EXCEPTION HANDLE */
--  DECLARE UNDO HANDLER FOR SQLEXCEPTION
--  BEGIN 
--    VALUES(SQLCODE,SQLSTATE) INTO I_SQLCODE,V_SQLSTATE;
--    SET OP_V_ERR_MSG = VALUE(OP_V_ERR_MSG,'')
--      ||'SYSTEM:SQLCODE='||RTRIM(CHAR(I_SQLCODE))
--      ||',SQLSTATE='||VALUE(RTRIM(V_SQLSTATE),'')||'; '
--    ; 
--  END; 
  DECLARE CONTINUE HANDLER FOR NOT FOUND SET SQL_CUR_AT_END=1;
  /* DECLARE TEMPORARY TABLE */
  -- DECLARE GLOBAL TEMPORARY TABLE BBDM_GROUP
  -- (
  --   BBDM INTEGER
  -- ) with replace on commit preserve rows not logged; 
  
  /* SQL PROCEDURE BODY */
  loopf1: --处理6要素
  for v1 as c1 cursor for 
    select distinct pfphdm 
    from YYZY.T_YYZY_ZXPF_LSB_R 
  do 
    call YYZY.P_YYZY_LSPF_SJDHB6(v1.pfphdm); 
  end for loopf1; 
  
  loopf2: --处理7要素
  for v2 as c2 cursor for 
    select distinct pfphdm 
    from JYHSF.T_JYHSF_ZSPF_LSB_R 
  do 
    call YYZY.P_YYZY_LSPF_SJDHB7(v2.pfphdm); 
  end for loopf2; 
  
END LB_MAIN; 

COMMENT ON PROCEDURE YYZY.P_YYZY_LSPF_SJDHB () IS '历史配方时间段合并';
