drop view YYZY.V_YYZY_YZPFD_FSSJCX_DY_GY;
create view YYZY.V_YYZY_YZPFD_FSSJCX_DY_GY 
( PFPHDM, PFPHMC, SCCJDM, PFNF, PFYF,
    YYDM, YYPC, TDYY, KSTLPC, JSTLPC,
    HJ, DPXS, JHCL, YYNF, YYLBDM,
    YYLBMC, YYCDMC, CDPX, YYDJMC, ZBZXMC,
    CBZXMC )
  as 
WITH TB_PFDB AS (
  SELECT M.PFPHDM, M.JSDM, M.ZBZXDM, M.ZBZXMC, M.YYDM, M.YYPC, 
    M.YYMC, MIN(M.KSTLPC) AS KSTLPC, MAX(M.JSTLPC) AS JSTLPC, M.CBZXDM, 
    M.CBZXMC, M.DPXS,M.BBH,M.PFNF, M.PFYF
  FROM YYZY.V_YYZY_YZPFD_FSSJCX AS M
  WHERE EXISTS(
        SELECT 1 FROM DIM.T_DIM_YYZY_PFPH 
        WHERE PFPHDM = M.PFPHDM AND JSRQ>=CURRENT_DATE 
          AND SCCJDM = 2
      )
  GROUP BY M.PFPHDM, M.JSDM, M.ZBZXDM, M.ZBZXMC, M.YYDM, M.YYPC, M.YYMC, M.CBZXDM, M.CBZXMC, M.DPXS, M.BBH, M.PFNF, M.PFYF
)
, TB_KSTLPC AS ( --牌号开始结束批次计算
  SELECT PFPHDM, PFNF, PFYF, MIN(KSTLPC) AS KSTLPC, MAX(JSTLPC) AS JSTLPC
  FROM TB_PFDB
  GROUP BY PFPHDM, PFNF, PFYF
)
, tb_dpxs as ( --角色单批箱数计算
  select PFPHDM, JSDM, PFNF, PFYF, sum(dpxs) as dpxs
  from TB_PFDB
  where (PFPHDM, JSDM, PFNF, PFYF, KSTLPC)in(
      select PFPHDM, JSDM, PFNF, PFYF, min(KSTLPC)
      from TB_PFDB 
      group by PFPHDM, JSDM, PFNF, PFYF
    )
  group by PFPHDM, JSDM, PFNF, PFYF
)
, tb_zlyy as ( --主料烟叶计算
  select t.pfphdm, t.jsdm, t.ZBZXDM, t.ZBZXMC, t.YYDM, t.YYPC, t.YYMC, 
    t.KSTLPC, t.JSTLPC, t.CBZXDM, t.CBZXMC, d.DPXS, t.BBH, t.PFNF, t.PFYF
  from (
      select pfphdm, jsdm, ZBZXDM, ZBZXMC, YYDM, YYPC, YYMC, 
        KSTLPC, JSTLPC, CBZXDM, CBZXMC, DPXS, BBH, PFNF, PFYF, 
        rownumber()over(partition by PFNF, PFYF, pfphdm, jsdm 
                        order by kstlpc, yydm
                        ) as xh
      from TB_PFDB
    ) as t 
    left join tb_dpxs as d 
      on (d.PFPHDM, d.JSDM, d.PFNF, d.PFYF)=(t.PFPHDM, t.JSDM, t.PFNF, t.PFYF)
  where xh = 1
)
,TB_ZLTDYY AS ( --替代烟叶计算
  SELECT M.PFPHDM, M.JSDM, M.ZBZXDM, M.ZBZXMC, M.YYDM, 
    M.YYPC, M.YYMC, M.KSTLPC, M.JSTLPC, M.CBZXDM, M.CBZXMC, 
    M.DPXS, M.BBH, M.PFNF, M.PFYF, C.YYDM AS TDYYDM, C.YYPC AS TDYYPC
  FROM tb_zlyy AS M 
    LEFT JOIN TB_PFDB AS C
      ON (M.PFPHDM, M.JSDM, M.PFNF, M.PFYF) = (C.PFPHDM, C.JSDM, C.PFNF, C.PFYF)
      AND NOT(M.YYDM = C.YYDM AND C.YYPC = M.YYPC)
)
, TB_ZLYY_HZ AS ( --主料烟叶dpxs汇总
  SELECT PFPHDM, ZBZXDM, ZBZXMC, YYDM, YYPC, YYMC, CBZXDM, 
    CBZXMC, SUM(DPXS) AS DPXS, BBH, PFNF, PFYF
  FROM tb_zlyy
  GROUP BY PFPHDM, ZBZXDM, ZBZXMC, YYDM, YYPC, YYMC, CBZXDM, CBZXMC, BBH, PFNF, PFYF
)
, TB_TDYY_GL AS (
  SELECT M.PFPHDM, M.ZBZXDM, M.ZBZXMC, M.YYDM, M.YYPC, M.YYMC, 
    M.CBZXDM, M.CBZXMC, M.DPXS, M.BBH, M.PFNF, M.PFYF, 
    SUBSTR(CHAR(Z.YYNF),3,2)||Z.YYCDMC||Z.YYDJMC||'('||C2.TDYYPC||')' AS TDYY
  FROM TB_ZLYY_HZ AS M 
    LEFT JOIN TB_ZLTDYY AS C1 
      ON (M.PFPHDM, M.PFNF, M.PFYF, M.YYDM, M.YYPC) = (C1.PFPHDM, C1.PFNF, C1.PFYF, C1.YYDM, C1.YYPC)
    LEFT JOIN 
      (SELECT PFPHDM, JSDM, PFNF, PFYF, TDYYDM, TDYYPC
        FROM TB_ZLTDYY
        UNION ALL
        SELECT M.PFPHDM, M.JSDM, M.PFNF, M.PFYF, C.YYDM, C.YYPC
        FROM TB_ZLTDYY AS M
          INNER JOIN JYHSF.T_JYHSF_ZSPF_SDB AS C
            ON M.PFPHDM = C.PFPHDM AND M.JSDM = C.JSDM
              AND C.JSRQ < DATE(TO_DATE(CHAR(PFNF*100*100+PFYF*100+1),'YYYYMMDD'))
              AND C.JSRQ > DATE(TO_DATE(CHAR(PFNF*100*100+PFYF*100+1),'YYYYMMDD')) - 1 MONTH
      ) AS C2(PFPHDM, JSDM, PFNF, PFYF, TDYYDM, TDYYPC)
      ON (C1.PFPHDM, C1.JSDM, C1.PFNF, C1.PFYF) = (C2.PFPHDM, C2.JSDM, C2.PFNF, C2.PFYF)
    LEFT JOIN YYZY.T_YYZY_YYZDBMX AS Z ON Z.YYDM=C2.TDYYDM 
)
, TB_TDYY_QC AS (
  SELECT PFPHDM, ZBZXDM, ZBZXMC, YYDM, YYPC, YYMC, CBZXDM, CBZXMC, DPXS, BBH, PFNF, PFYF, TDYY
  FROM TB_TDYY_GL
  GROUP BY PFPHDM, ZBZXDM, ZBZXMC, YYDM, YYPC, YYMC, CBZXDM, CBZXMC, DPXS, BBH, PFNF, PFYF, TDYY
)

, TB_TDYY AS (
  SELECT PFPHDM, ZBZXDM, ZBZXMC, YYDM, YYPC, YYMC, 
    CBZXDM, CBZXMC, DPXS, BBH, PFNF, PFYF, 
    REPLACE(REPLACE(XML2CLOB(XMLAGG(XMLELEMENT(NAME A, VALUE(TDYY,'')||';'))),'</A>',''),'<A>','') AS TDYY
  FROM TB_TDYY_QC 
  GROUP BY PFPHDM, ZBZXDM, ZBZXMC, YYDM, YYPC,  YYMC, CBZXDM, CBZXMC, DPXS, BBH, PFNF, PFYF
)
,YSCJH_TMP AS ( 
  SELECT JHNF, JHYF, YHBS, CJDM, JHCL 
  FROM YYZY.T_YYZY_YSCJH 
  WHERE (JHNF,JHYF,BBH)IN(
        SELECT JHNF,JHYF,MAX(BBH) FROM YYZY.T_YYZY_YSCJH GROUP BY JHNF,JHYF
      ) 
    AND ZYBJ='1'
) 
,YSCJH_RSLT AS (   
  SELECT PFPHDM, JHNF, JHYF, SUM(JHCL) AS JHCL 
  FROM YSCJH_TMP AS A 
    LEFT JOIN (
        SELECT PFPHDM, PFPHBS, PFPHMC, YHBS, SCCJDM, KSRQ, JSRQ 
        FROM DIM.T_DIM_YYZY_PFPH 
        WHERE CURRENT DATE BETWEEN KSRQ AND JSRQ 
      ) AS B 
      ON A.YHBS=B.YHBS AND A.CJDM=B.SCCJDM 
  GROUP BY PFPHDM,JHNF,JHYF
)
,RSCJH AS (
  SELECT PFPHDM, B.RIQI AS KSRQ, B.RIQI AS JSRQ, JHCL_AVG AS XHYZL 
  FROM (SELECT PFPHDM, JHRQ AS KSRQ, JHRQ AS JSRQ, JHCL  AS JHCL_AVG
      FROM YYZY.T_YYZY_RSCJH_LSB
      WHERE CURRENT DATE - 3 MONTH < JHRQ 
      UNION ALL 
      SELECT PFPHDM,KSRQ,JSRQ, JHCL_AVG
      FROM YYZY.T_YYZY_RSCJHB_WHB
    ) AS A , 
    DIM.T_DIM_YYZY_DATE B
  WHERE B.RIQI BETWEEN A.KSRQ AND A.JSRQ 
) 
,GPJS_TMP1 AS (
  SELECT PFPHDM, KSRQ, JSRQ, JHCL_AVG AS XHYZL 
  FROM YYZY.T_YYZY_RSCJHB_WHB 
  WHERE PFPHDM IN(
        SELECT PFPHDM
        FROM YYZY.T_YYZY_PFPH_CFG
        WHERE GPBJ<>'0'
      )
) 
,GPJS_TMP2 AS(  
  SELECT A.RIQI, B.PFPHDM, B.KSRQ, B.JSRQ, B.XHYZL
  FROM  DIM.T_DIM_YYZY_DATE AS A,GPJS_TMP1 AS B
  WHERE A.RIQI BETWEEN B.KSRQ AND B.JSRQ
)
, GPJS_TMP3 AS(
  SELECT RIQI, YEAR(RIQI) AS JHNF, MONTH(RIQI) AS JHYF, PFPHDM,
    KSRQ, JSRQ, XHYZL
  FROM GPJS_TMP2
)
,RSLT AS (
  SELECT PFPHDM, JHNF, JHYF, SUM(XHYZL) AS JHCL, 1 AS BJ
  FROM( 
      SELECT PFPHDM, YEAR(KSRQ) AS JHNF, MONTH(KSRQ) AS JHYF, XHYZL
      FROM RSCJH 
    ) as t
  GROUP BY PFPHDM,JHNF,JHYF 
  UNION ALL
  SELECT PFPHDM, JHNF, JHYF, JHCL, 2 AS BJ
  FROM YSCJH_RSLT 
  UNION ALL
  SELECT PFPHDM, JHNF , JHYF, SUM(XHYZL) AS JHCL, 3 AS BJ
  FROM GPJS_TMP3
  GROUP BY JHNF,JHYF,PFPHDM 
)
,YDSCJH AS(
  SELECT PFPHDM, JHNF, JHYF, JHCL 
  FROM RSLT 
  WHERE (PFPHDM,BJ) IN (
        SELECT PFPHDM,MAX(BJ) 
        FROM RSLT WHERE JHCL IS NOT NULL 
        GROUP BY PFPHDM
      ) 
) 
, TB_RES AS (
  SELECT M.PFPHDM, H.PFPHMC, 2 AS SCCJDM, M.PFNF, M.PFYF, M.YYDM, M.YYPC, 
    LEFT(REPLACE(M.TDYY,';;',';'),LENGTH(REPLACE(M.TDYY,';;',';'))-1) AS TDYY, 
    P.KSTLPC, P.JSTLPC, (P.JSTLPC - P.KSTLPC + 1) AS HJ, M.DPXS, 
    VALUE(J.JHCL,0) AS JHCL, Y.YYNF, Y.YYLBDM, Y.YYLBMC, Y.YYCDMC, 
    Y.CDPX, Y.YYDJMC, M.ZBZXMC, M.CBZXMC
  FROM TB_TDYY AS M
    LEFT JOIN TB_KSTLPC AS P
      ON (M.PFPHDM, M.PFNF, M.PFYF) = (P.PFPHDM, P.PFNF, P.PFYF)
    LEFT JOIN YDSCJH AS J
      ON M.PFPHDM = J.PFPHDM
      AND J.JHNF = M.PFNF
      AND J.JHYF = M.PFYF
    LEFT JOIN YYZY.T_YYZY_YYZDBMX AS Y 
      ON Y.YYDM=M.YYDM 
    LEFT JOIN DIM.T_DIM_YYZY_PFPH AS H 
      ON M.PFPHDM = H.PFPHDM 
      AND JSRQ>=CURRENT_DATE
)
SELECT PFPHDM, PFPHMC, SCCJDM, PFNF, PFYF, YYDM, YYPC, TDYY, KSTLPC, JSTLPC,
    HJ, DPXS, JHCL, YYNF, YYLBDM,YYLBMC, YYCDMC, CDPX, YYDJMC, ZBZXMC, CBZXMC 
FROM TB_RES;
