SET SCHEMA = YYZY;

SET CURRENT PATH = SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,ETLUSR;

CREATE VIEW YYZY.V_YYZY_YZPFD_FSSJCX_DY_GY
    ( PFPHDM, PFPHMC, SCCJDM, PFNF, PFYF,
    YYDM, YYPC, TDYY, KSTLPC, JSTLPC,
    HJ, DPXS, JHCL, YYNF, YYLBDM,
    YYLBMC, YYCDMC, CDPX, YYDJMC, ZBZXMC,
    CBZXMC )
AS
WITH 
YSSJ AS (
  select A.PFPHDM, B.PFPHMC, B.SCCJDM, A.JSDM, A.YYDM, A.YYPC, 
    MIN(A.KSTLPC)OVER(PARTITION BY A.PFPHDM,A.PFNF,A.PFYF) AS KSTLPC, 
    MAX(A.JSTLPC)OVER(PARTITION BY A.PFPHDM,A.PFNF,A.PFYF) AS JSTLPC, 
    A.DPXS, A.PFNF, A.PFYF, 
    RIGHT(RTRIM(CHAR(C.YYNF)),2) AS YYNF, C.YYLBDM, C.YYLBMC, C.YYCDMC, 
    C.CDPX, C.YYDJMC, A.ZBZXMC, A.CBZXMC, 
    dense_rank()over(partition by a.PFPHDM,a.PFNF,a.PFYF order by a.KSTLPC) as BH 
  from YYZY.V_YYZY_YZPFD_FSSJCX AS A 
    LEFT JOIN DIM.T_DIM_YYZY_PFPH AS B 
      ON A.PFPHDM=B.PFPHDM AND CURRENT DATE BETWEEN B.KSRQ AND B.JSRQ 
    LEFT JOIN YYZY.T_YYZY_YYZDBMX AS C ON A.YYDM=C.YYDM 
  WHERE B.SCCJDM=2 
) 
, ZPFSJ_TMP1 AS ( 
  SELECT A.PFPHDM, A.PFPHMC, A.SCCJDM, A.PFNF, A.PFYF, A.JSDM, A.YYDM, 
    A.YYPC, A.KSTLPC, A.JSTLPC, A.JSTLPC-A.KSTLPC+1 AS HJ, A.DPXS, 
    A.YYNF, A.YYLBDM, A.YYLBMC, A.YYCDMC, A.CDPX, A.YYDJMC, A.ZBZXMC, 
    A.CBZXMC, CASE WHEN B.YYDM IS NULL THEN 1 ELSE 2 END AS PDBJ 
  FROM YSSJ AS A 
    LEFT JOIN YSSJ AS B 
      ON A.PFPHDM=B.PFPHDM AND A.JSDM=B.JSDM AND A.YYDM=B.YYDM 
      AND A.PFNF=B.PFNF AND A.PFYF=B.PFYF AND B.BH=2 
  WHERE A.BH=1 
) 
, ZPFSJ_TMP2 AS ( 
  SELECT PFPHDM, PFPHMC, SCCJDM, PFNF, PFYF, JSDM, YYDM, YYPC, 
    KSTLPC, JSTLPC, HJ, DPXS, YYNF, YYLBDM, YYLBMC, YYCDMC, CDPX, 
    YYDJMC, ZBZXMC, CBZXMC, 
    DENSE_RANK()OVER(PARTITION BY PFPHDM,JSDM,PFNF,PFYF,KSTLPC,JSTLPC ORDER BY PDBJ,YYDM) AS PDBJ 
  FROM ZPFSJ_TMP1 
) 
,ZPFSJ AS ( 
  SELECT PFPHDM, PFPHMC, SCCJDM, PFNF, PFYF, JSDM, YYDM, YYPC, KSTLPC, JSTLPC, HJ, DPXS, YYNF, YYLBDM, YYLBMC, YYCDMC, CDPX, YYDJMC, ZBZXMC, CBZXMC 
  FROM ZPFSJ_TMP2 
  WHERE PDBJ=1 
) 
,TDYY AS ( 
  SELECT DISTINCT PFPHDM, JSDM, YYDM, YYPC, PFNF, PFYF, 
    YYNF||YYCDMC||YYDJMC||'('||YYPC||')' AS TDYY 
  FROM YSSJ 
  WHERE (PFPHDM,JSDM,YYDM,YYPC,PFNF,PFYF) NOT IN (
      SELECT PFPHDM,JSDM,YYDM,YYPC,PFNF,PFYF 
      FROM ZPFSJ
    ) 
  ORDER BY PFPHDM,JSDM 
) 
,SJZH_TMP1 AS ( 
  SELECT A.PFPHDM, A.PFPHMC, A.SCCJDM, A.PFNF, A.PFYF, A.YYDM, 
    A.YYPC, A.KSTLPC, A.JSTLPC, A.HJ, SUM(A.DPXS) AS DPXS, A.YYNF, 
    A.YYLBDM, A.YYLBMC, A.YYCDMC, A.CDPX, A.YYDJMC, A.ZBZXMC, A.CBZXMC 
  FROM ZPFSJ AS A 
  GROUP BY PFPHDM,PFPHMC,SCCJDM,PFNF,PFYF,YYDM,YYPC,KSTLPC,
    JSTLPC,HJ,YYNF,YYLBDM,YYLBMC,YYCDMC,CDPX,YYDJMC,ZBZXMC,CBZXMC 
) 
, SJZH AS ( 
  SELECT A.PFPHDM, A.PFPHMC, A.SCCJDM, A.PFNF, A.PFYF, A.YYDM, A.YYPC, 
    A.KSTLPC, A.JSTLPC, A.HJ, A.DPXS, C.TDYY, A.YYNF, A.YYLBDM, A.YYLBMC, 
    A.YYCDMC, A.CDPX, A.YYDJMC, A.ZBZXMC, A.CBZXMC 
  FROM SJZH_TMP1 AS A 
  LEFT JOIN ZPFSJ AS B 
    ON A.YYDM=B.YYDM AND A.PFPHDM=B.PFPHDM AND A.YYPC=B.YYPC AND A.PFNF=B.PFNF AND A.PFYF=B.PFYF 
  LEFT JOIN TDYY AS C 
    ON B.PFPHDM=C.PFPHDM AND B.JSDM=C.JSDM AND B.PFNF=C.PFNF AND B.PFYF=C.PFYF 
  GROUP BY A.PFPHDM,A.PFPHMC,A.SCCJDM,A.PFNF,A.PFYF,A.YYDM,A.YYPC,
    A.KSTLPC,A.JSTLPC,C.TDYY,A.DPXS,A.HJ,A.YYNF,A.YYLBDM,A.YYLBMC,
    A.YYCDMC,A.CDPX,A.YYDJMC,A.ZBZXMC,A.CBZXMC 
) 
, YDSCJH AS ( 
  select B.PFPHDM, JHNF, JHYF, SUM(JHCL) AS JHCL 
  from YYZY.T_YYZY_YSCJH as a 
    left join DIM.T_DIM_YYZY_PFPH as b 
      on a.yhbs=b.yhbs and int(a.cjdm)=int(b.sccjdm) 
  where (A.yhbs,A.CJDM,A.jhnf,A.jhyf,A.bbh) in (
    select yhbs,CJDM,jhnf,jhyf,max(bbh) 
    from YYZY.T_YYZY_YSCJH 
    group by yhbs,CJDM,jhnf,jhyf
  ) 
  GROUP BY B.PFPHDM,JHNF,JHYF 
) 
, RES AS ( 
  SELECT A.PFPHDM, A.PFPHMC, A.SCCJDM, A.PFNF, A.PFYF, A.YYDM, A.YYPC, 
    REPLACE(replace(xml2clob(xmlagg(xmlelement(name a, VALUE(TDYY,'')||';'))),'</A>',''),'<A>','') as TDYY, 
    A.KSTLPC, A.JSTLPC, A.HJ, A.DPXS AS DPXS, VALUE(B.JHCL,0) AS JHCL, A.YYNF, A.YYLBDM, A.YYLBMC, A.YYCDMC, 
    A.CDPX, A.YYDJMC, A.ZBZXMC, A.CBZXMC 
  FROM SJZH AS A 
    LEFT JOIN YDSCJH AS B ON A.PFPHDM=B.PFPHDM AND A.PFNF=B.JHNF AND A.PFYF=B.JHYF 
  GROUP BY a.PFPHDM,a.PFPHMC,a.SCCJDM,a.PFNF,a.PFYF,a.YYDM,
    a.YYPC,a.KSTLPC,a.JSTLPC,a.DPXS,b.jhcl,a.HJ,a.TDYY,a.YYNF,
    a.YYLBDM,a.YYLBMC,a.YYCDMC,a.CDPX,a.YYDJMC,a.ZBZXMC,a.CBZXMC 
) 
SELECT PFPHDM, PFPHMC, SCCJDM, PFNF, PFYF, YYDM, YYPC, 
  SUBSTR(TDYY,1,LENGTH(VALUE(TDYY,''))-1) AS TDYY, KSTLPC, 
  JSTLPC, HJ, DPXS, JHCL, YYNF, YYLBDM, YYLBMC, YYCDMC, 
  CDPX, YYDJMC, ZBZXMC, CBZXMC 
FROM RES
;

GRANT CONTROL ON TABLE YYZY.V_YYZY_YZPFD_FSSJCX_DY_GY TO USER ETLUSR;

GRANT SELECT ON TABLE YYZY.V_YYZY_YZPFD_FSSJCX_DY_GY TO USER ETLUSR WITH GRANT OPTION;

GRANT SELECT ON TABLE YYZY.V_YYZY_YZPFD_FSSJCX_DY_GY TO USER APPUSR WITH GRANT OPTION;

GRANT SELECT ON TABLE YYZY.V_YYZY_YZPFD_FSSJCX_DY_GY TO USER ETLUSR WITH GRANT OPTION;

