SET SCHEMA = MD;

CREATE PROCEDURE MD.P_ETL_MAIN_DS ( IN TGTTABLE VARCHAR(128) )
  SPECIFIC SQL120113205510700
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
BEGIN

    DECLARE SJK_NAME VARCHAR(50) DEFAULT '';
    DECLARE SRCTABLE VARCHAR(50) DEFAULT '';
    DECLARE LOADTYPE VARCHAR(1) DEFAULT '';
    DECLARE LOADFIELD VARCHAR(255) DEFAULT '';
    DECLARE LOADVALUE VARCHAR(255) DEFAULT '';
    
    SET SJK_NAME='130.130.160.6-DDS';
    
    SET SRCTABLE = (select value(a.DSLSB,'') from MD.N_ETL_DSLSB as a where a.SJK=SJK_NAME and a.MBB=TGTTABLE);
    
    SET LOADTYPE = (select value(a.JZFS,'') as LOADTYPE from MD.N_MD_DXYSJJC as a where a.DXLX='T' and a.SJK=SJK_NAME and a.DXMC=TGTTABLE);
    
    SET LOADFIELD = (select value(a.JZZD,'') as LOADFIELD from MD.N_MD_DXYSJJC as a where a.DXLX='T' and a.SJK=SJK_NAME and a.DXMC=TGTTABLE);
    
    SET LOADVALUE = (select value(a.JZZ,'') as LOADVALUE from MD.N_MD_DXYSJJC as a where a.DXLX='T' and a.SJK=SJK_NAME and a.DXMC=TGTTABLE);

    call MD.P_ETL_MAIN(TGTTABLE,SRCTABLE,LOADTYPE,LOADFIELD,LOADVALUE);

  END;
